name: Daily Scheduled Code Run

on:
  # KST (한국 시간) 오전 7시는 UTC 기준 22시 (오후 10시) 입니다.
  # '0 22 * * *' : 매일 22시 0분에 실행
  schedule:
    - cron: "0 22 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    # [핵심] GitHub Secrets에 저장된 환경 변수를 워크플로우에서 사용하도록 설정
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout repository code
        # 레포지토리의 코드를 Runner (실행 환경)로 가져옵니다.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" # 원하는 Python 버전을 지정하세요.

      - name: Install dependencies
        # requirements.txt 파일에 명시된 모든 의존성 패키지를 설치합니다.
        run: |
          pip install -r requirements.txt

      - name: Execute the main code
        run: |
          echo "Starting script run with environment variables..."
          python main.py
          echo "Script execution finished."

      - name: Commit processed posts file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add processed_posts.txt
          git commit -m "feat: Add processed post [skip ci]"
          git push
